image: rocker/tidyverse

stages:
  - check
  - test

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_SUGGESTS_ONLY: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_CACHE: "$CI_PROJECT_DIR/ci/lib/apt-cache"
  CRAN_MIRROR: "https://cloud.r-project.org"
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  R_LIBS: "$CI_PROJECT_DIR/ci/lib"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs"
  NOT_CRAN: "true"

getready:
  stage: .pre
  script:
    - mkdir -p $R_LIBS_USER
    - mkdir -p $APT_CACHE
    - R -e 'install.packages(c("shinycssloaders", "shinydashboard","shinyAce","leaflet", "dataRetrieval", "kableExtra","shiny", "EnvStats", "ggpmisc"), repos = Sys.getenv("CRAN_MIRROR"), lib = Sys.getenv("R_LIBS_USER"))'
  cache:
    paths:
     - $R_LIBS_USER
  artifacts:
    paths:
     - $R_LIBS_USER

buildcheck:
  stage: check
  script:
    - mkdir -p $BUILD_LOGS_DIR
    - apt-get update
    - apt-get -o dir::cache::archives=${APT_CACHE} install -y --no-install-recommends qpdf pandoc pandoc-citeproc
    - R CMD build . --no-build-vignettes --no-manual
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", error_on = "warning", check_dir = Sys.getenv("BUILD_LOGS_DIR"))'
  artifacts:
    paths:
      - $BUILD_LOGS_DIR

unittests:
  stage: test
  dependencies:
    - getready
    - buildcheck
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

covertests:
  stage: test
  dependencies:
    - getready
    - buildcheck
  script:
    - R -e 'covr::package_coverage()'
  coverage: '/Coverage: \d+.\d+\%/'

