---
title: "Principal Aquifers"
output: 
  rmarkdown::html_vignette
editor_options: 
  chunk_output_type: console
vignette: >
  %\VignetteIndexEntry{Principal Aquifers}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 7)

library(HASP)
library(kableExtra)
library(dplyr)

```

# Introduction

More information can be found here:
<https://groundwaterwatch.usgs.gov/composite/help/CompositeGroundwaterLevelHelpDocument.docx.html>

<https://groundwaterwatch.usgs.gov/composite/help/compositewaterlevels_helpdocument_7-7-2016.htm>



```{r setupData, echo=FALSE}


summary_aquifers_disp <- summary_aquifers |> 
  select(long_name, aquiferCd=nat_aqfr_cd)

kable(summary_aquifers_disp) |>
  kable_styling(bootstrap_options = c("striped", "hover")) |> 
  column_spec(1, width = "50em")

```
