---
title: "Single Site Water Level"
output: 
  rmarkdown::html_vignette
editor_options: 
  chunk_output_type: console
vignette: >
  %\VignetteIndexEntry{Water Level Single Site Information}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE,
               warning = FALSE,
               message = FALSE,
               fig.width = 7,
               fig.height = 7)
library(dplyr)
library(tidyr)
library(ggplot2)
library(HASP)

options(knitr.kable.NA = '')
```

This vignette shows how to use `HASP` and other R tools to reproduce:

https://fl.water.usgs.gov/mapper/waterlevel_site_info.php?site=263819081585801

First, use the `dataRetrieval` package to get site information:

## DESCRIPTION

```{r siteInfo, echo=TRUE, results='asis'}
library(dataRetrieval)
library(HASP)
library(dplyr)
library(tidyr)

siteID <- "263819081585801"
site_metadata <- site_summary(siteID, markdown = TRUE)
```

## AVAILABLE DATA

```{r whatData, echo=TRUE}
data_info <- data_available(siteID)
kable(data_info)
```

## Water Level Data and Analysis

```{r weeklyFrequency, echo = TRUE}

parameterCd <- "62610"
statCd <- "00001"
# gw_level_dv <- dataRetrieval::readNWISdv(siteID, parameterCd, statCd = statCd)
# Use package sample data:
gw_level_dv <- L2701_example_data$Daily
weekly_frequency_plot(gw_level_dv, parameterCd, statCd, 
                      plot_title = "263819081585801 L -2701 ")

weekly_freq_table <- weekly_frequency_table(gw_level_dv,
                                            parameterCd,
                                            statCd) %>%
  select(week, minMed, p10, p25, p50, p75, p90, maxMed, nYears) %>%
  rename("Week of the year" = week,
         "Lowest median" = minMed,
         "10th percentile" = p10,
         "25th percentile" = p25,
         "50th percentile" = p50,
         "75th percentile" = p75,
         "Highest median" = maxMed,
         "Number of years" = nYears)
kable(head(weekly_freq_table, 10))

```

```{r dailyPlot}
parameterCd <- "62610"
statCd <- "00001"
# gw_level_dv <- dataRetrieval::readNWISdv(siteID, parameterCd, statCd = statCd)
# Use package sample data:
gw_level_dv <- L2701_example_data$Daily
daily_gwl_2yr_plot(gw_level_dv, p_code_dv = parameterCd, statCd = statCd,
                   plot_title = "263819081585801 L -2701",
                   historical_stat = "mean",
                   month_breaks = TRUE)

daily_table <- daily_frequency_table(gw_level_dv, p_code_dv = parameterCd, statCd = statCd) %>%
  rename("Day of year" = DOY,
         "Maximum" = max,
         "Mean" = mean,
         "Minimum" = min,
         "Available points" = points)
kable(head(daily_table, 10))

```

### Water level trends

```{r trend_dv}
# gwl_data <- dataRetrieval::readNWISgwl(siteID)
# Use package sample data:
gwl_data <- L2701_example_data$Discrete

gwl_plot_all(gw_level_dv, 
             gwl_data, add_trend = TRUE,
             p_code_dv = parameterCd)
```

```{r gwl_trend_table}
dv_trend <- kendell_test_5_20_years(gw_level_dv, 
                     seasonal = FALSE,
                     enough_5 = 6,
                     enough_20 = 10,
                     date_col = "Date",
                     value_col = "X_62610_00001")

dv_trend_sea <- kendell_test_5_20_years(gw_level_dv, 
                     seasonal = TRUE,
                     enough_5 = 6,
                     enough_20 = 10,
                     date_col = "Date",
                     value_col = "X_62610_00001")

gwl_trend_sea <- kendell_test_5_20_years(gwl_data, 
                     seasonal = TRUE,
                     enough_5 = 1,
                     enough_20 = 1,
                     date_col = "lev_dt",
                     value_col = "sl_lev_va")

gwl_trend_not_sea <- kendell_test_5_20_years(gwl_data, 
                     seasonal = FALSE,
                     enough_5 = 1,
                     enough_20 = 1,
                     date_col = "lev_dt",
                     value_col = "sl_lev_va")

kable(gwl_trend, digits = 3)
```
