---
title: "Composite Hydrograph"
output: 
  rmarkdown::html_vignette
editor_options: 
  chunk_output_type: console
vignette: >
  %\VignetteIndexEntry{Composite Hydrograph}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      fig.width = 7,
                      fig.height = 7)
library(dplyr)
library(tidyr)
library(ggplot2)
library(leaflet)
```

# Introduction

More information can be found here:
<https://groundwaterwatch.usgs.gov/composite/help/CompositeGroundwaterLevelHelpDocument.docx.html>

<https://groundwaterwatch.usgs.gov/composite/help/compositewaterlevels_helpdocument_7-7-2016.htm>


# Basin and Range basin-fill aquifers

see <https://groundwaterwatch.usgs.gov/compositeaquifers.asp?ncd=BRF>.

## Get Data


```{r setupData, echo=FALSE}
library(HASP)

aquifer_long_name <- "Basin and Range basin-fill aquifers"

aquiferCd <- summary_aquifers$nat_aqfr_cd[summary_aquifers$long_name == aquifer_long_name]

states <- unlist(summary_aquifers$states[summary_aquifers$long_name == aquifer_long_name])

cat("Aquifer code: ", aquiferCd)
cat("In states: ", paste(states, collapse = ", ") )


```

```{r dataRetrival, eval=FALSE}
library(HASP)
end_date <- "2019-12-31"
state_date <- "1989-12-31"

aquifer_data <- get_aquifer_data(aquiferCd, 
                                 state_date, 
                                 end_date)

```

```{r dataRetrival_sample, eval=TRUE, echo=FALSE}
aquifer_data <- aquifer_data
```

## Map It

```{r mapIt}

map <- map_hydro_data(aquifer_data,
                      "lev_va", 30)
map

```

## Composite

```{r graphIt}

plot_composite_data(aquifer_data, "lev_va", 30) +
    ggtitle(label = aquifer_long_name)

```


## Normalized Composite

```{r norm}

plot_normalized_data(aquifer_data, "lev_va", 30) +
  ggtitle(label = aquifer_long_name)
```